### ISSUE TITLE
motor selective stop task 4 + probably all stop tasks

### ISSUE THREAD

**Issue by bissettp** [expfactory/expfactory-experiments#147]
The go stimuli were proportioned strangely, especially in relation to the size of the stop stimulus. The triangle is nearly touching the surrounding stop stimulus, which makes those two stimuli more like a single compound stimulus. Perhaps we should use the go stimuli from the action-valence stopping experiment that Jamie coded. I believe this size/proportion issue has been fixed there.

**Comment by IanEisenberg** [comment]
I think this is because you had the web console open (just a guess). Jamie's script uses mine exactly. I can make the stop signal slightly further away regardless.

**Comment by bissettp** [comment]
I believe that Jamie has made adjustments since she adopted your code, because when we started to pilot the action-valence experiment it had similar proportioning problems to the one I mention here

**Comment by IanEisenberg** [comment]
I asked her, she didn't remember. Regardless, I'll look at the gmparadigm
and make sure they are the same (and working nicely)

On Thu, Feb 4, 2016 at 6:33 PM, bissettp <notifications@github.com> wrote:

> I believe that Jamie has made adjustments since she adopted your code,
> because when we started to pilot the action-valence experiment it had
> similar proportioning problems to the one I mention here
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/expfactory/expfactory-experiments/issues/147#issuecomment-180163646>
> .
>



-- 
Best,
Ian

**Comment by bissettp** [comment]
What was the resolution for this issue?

**Comment by IanEisenberg** [comment]
I slightly changed the sizes, but I'm sure the issue came from you having
the web console up. Regardless, I made my code similar to Jamies. I had
made certain shapes slightly bigger or smaller depending on their
subjective 'mass'. The idea was that similar size triangles and squares
actually look different because the square has more area...so I made the
square a bit smaller. Jamie didn't do this. That is the only difference.

On Thu, Feb 11, 2016 at 12:28 PM, bissettp <notifications@github.com> wrote:

> What was the resolution for this issue?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/expfactory/expfactory-experiments/issues/147#issuecomment-183049356>
> .
>



-- 
Best,
Ian
