### ISSUE TITLE
Vague vs Concrete Bonuses

### ISSUE THREAD

**Issue by bissettp** [expfactory/expfactory-experiments#154]
Do we want to be vague on the bonuses that subjects can receive in the task? It would seem to be a stronger motivation to perform as well as possible if subjects have an explicit understanding of how they'll be rewarded, as at least if the explicit reward is non-trivial.

**Comment by vsoch** [comment]
I don't think that the bonuses / things about payment should be hard coded into the task.

**Comment by IanEisenberg** [comment]
Yeah, I suppose if we leave the bonuses vague "you will get bonuses based on performance" they may be less motivating, but I think it is equally likely that if we say "you can earn up to 30 cents more" they will be less motivating. 

Besides that general point is vsoch's (which is a point about experiment factory rather than UH2 grant) - hard coding amounts makes it difficult for others to use the tasks. Given that, I think we should keep it vague.

**Comment by bissettp** [comment]
I don't feel strongly about this. But if we are leaving it vague then we should perhaps be similarly vague across tasks with rewards

**Comment by IanEisenberg** [comment]
Agreed.

On Thu, Feb 4, 2016 at 6:30 PM, bissettp <notifications@github.com> wrote:

> I don't feel strongly about this. But if we are leaving it vague then we
> should perhaps be similarly vague across tasks with rewards
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/expfactory/expfactory-experiments/issues/154#issuecomment-180163246>
> .
>



-- 
Best,
Ian
