### ISSUE TITLE
UPPS_impulsivity 1

### ISSUE THREAD

**Issue by bissettp** [expfactory/expfactory-experiments#194]
![screen shot 2016-02-08 at 2 29 04 pm](https://cloud.githubusercontent.com/assets/9681335/12901407/60a6dce6-ce70-11e5-91ff-aed7830b731d.png)

The instruction seems to suggest that subjects should be responding based the degree to which people act or think according to the statement. Then the actual questions are asking about the subjects themselves (i.e., subject of sentence is "I"). It seems that the instructions need to be better aligned with the questions. However, if this is the exact instructions from the measure then perhaps we should stick with this (confusing) precedent.

**Comment by zenkavi** [comment]
Here is the exact wording of the instructions from the original questionnaire: "Below are a number of statement that describe ways in which people act and think. For each statement, please indicate how much you agree or disagree with the statement. If you Agree Strongly circle 1, if you Agree Somewhat circle 2, if you Disagree somewhat circle 3, and if you Disagree Strongly circle 4. Be sure to indicate your agreement or disagreement for every statement below. Also, there are question son the following pages." 

I removed the instructions on the circling specific numbers since the way we are displaying the options doesn't involve them (theirs did because they had columns of numbers to respond to instead of presenting all text options below each question as is customary in paper-based questionnaires to save paper). I also changed the "below" to "following pages" and removed the last sentence since it became redundant. 

I think this keeps us closest to the instructions by modifying it to be compatible with this computerized version and we should keep it, perhaps somewhat confusing, but at least not deliberately different than the original.

**Comment by zenkavi** [comment]
@bissettp @IanEisenberg the current instructions don't seem to involve anything on decision strategies to be removed. They might only be a bit confusing otherwise. Do we still want to make changes to these instructions or keep them as they are (i.e. slightly modified from the original)?

**Comment by zenkavi** [comment]
To be discussed on 2/25 along with all other instructions.
