### ISSUE TITLE
adaptive_n_back

### ISSUE THREAD

**Issue by bissettp** [expfactory/expfactory-experiments#195]
As Ian and I have discussed, I think that including both lower and upper case letters is an unnecessary complication that differs from most of the N-back work in the literature (in which the stimulus you are looking for is an exact perceptual match to the stimulus N stimuli back). I recommend using only capital letters.

**Comment by IanEisenberg** [comment]
Russ's response:
well, seems like it will definitely make it more difficult, and I’m guessing that difficulty is a good thing for us (better dynamic range) so I would argue to keep the mixed case unless there is a stronger argument against.

The original article I took from (this one: http://www.sciencedirect.com/science/article/pii/S1053811905001424) made this argument:

"Briefly, subjects were asked to indicate whether a letter presented on a screen (the “target” stimulus) matched a letter previously presented (the “cue” stimulus). In order to reduce visual and phonological strategies, we used phonologically closed letters with upper and lower case. Thus, only the following letters were presented: b, B, d, D, g, G, p, P, t, T, v, V. Subjects were told to ignore the case of the letters. "

**Comment by bissettp** [comment]
In an adaptive N-back task, difficulty is titrated so I suspect that we'll get a nice range with mixed case or only capital. My main argument for using only uppercase is it's easier to instruct/understand and it aligns more closely with most N-back tasks. 

With all that being said, I don't feel strongly about this one way or the other.
