### ISSUE TITLE
UPPS&P

### ISSUE THREAD

**Issue by magvt** [expfactory/expfactory-experiments#266]
1) Next button issues
2) Tiny response buttons
3) Responses seem repetitive - maybe by design
4) Progress bar on last screen of questions shows more to do, but it's just the next page saying I'm done.

**Comment by zenkavi** [comment]
1. Are the next button issues the same as questionnaires, i.e. doesn't appear at the end of the screen but at random places (in the middle and not allowing you to click on it)?

2. Are "tiny" response buttons referring to the radio buttons for each question? Is this an issue for all questionnaires (and other tasks that have radio buttons)? 

3. This is a questionnaire that combines questions from a few questionnaires trying to measure the same thing so I suspect the "repetitiveness" is related to this but please let me know if you think otherwise.

4. Progress bar on each screen keeps track of work that has been done. Work is considered "done" once the next button is pressed. So on the first page it shows a blank progress bar because nothing has been done submitted by clicking next yet. On the last page it has, in this case, a quarter of the bar left because the last (4th) page hasn't yet been submitted. Do you think this is confusing to participants and that the progress bar instead should reflect the page you are on (i.e. on the first page it would be a quarter full in a four-page survey without having done anything yet and the last page it would be completely filled)?

**Comment by magvt** [comment]
Hi Zeynep-

1)      Yes – same as others: next button appears In middle of screen, and when clicked, sends to bottom (not top) of next screen.

2)      Yes, sorry – radio buttons too small.  I don’t recall it being an issue except for this and Impulse_Venture.

3)      Unless the repetition is designed to determine consistency is responses, I’d eliminate the questions that repeat.  I found it annoying.

4)      I do think the progress bar isn’t accurate.  I understand how it’s programmed, but I was surprised when I got to the end because I thought I had more to do.  I like your idea of it reflecting the page you’re on.



Thanks!

mag

**Comment by zenkavi** [comment]
1. Ok fixed the scrolling issue as I mentioned in another comment as well (though this will not be reflected in the version of the tasks you are testing now). The issue of the next button not appearing at end of the first page is still in progress but it's a global problem so I'm thinking of that separate from this specific questionnaire. 

2. I have now seen the radio button size as an issue on multiple questionnaires and like the next button issue will try to resolve it globally and separate from this specific questionnaire.

3. Repetition is indeed annoying (sorry) but unfortunately intended and to keep it consistent with how the questionnaire has been designed originally I cannot fix this. 

4. I agree with your thoughts on the progress bar. I changed this as well (again not reflected in the versions you are testing) so now it doesn't start at 0 but even on the first page fills in e.g. a quarter of the bar of a four page survey and all of it on the last page. No need to report it for others you are testing. 

Since there are no other issue specific to this questionnaire I am closing this issue as well but please feel free to reopen if you disagree.

**Comment by magvt** [comment]
All sounds good! Thanks Zeynep.

On Feb 18, 2016, at 5:25 PM, Zeynep Enkavi <notifications@github.com<mailto:notifications@github.com>> wrote:


  1.  Ok fixed the scrolling issue as I mentioned in another comment as well (though this will not be reflected in the version of the tasks you are testing now). The issue of the next button not appearing at end of the first page is still in progress but it's a global problem so I'm thinking of that separate from this specific questionnaire.

  2.  I have now seen the radio button size as an issue on multiple questionnaires and like the next button issue will try to resolve it globally and separate from this specific questionnaire.

  3.  Repetition is indeed annoying (sorry) but unfortunately intended and to keep it consistent with how the questionnaire has been designed originally I cannot fix this.

  4.  I agree with your thoughts on the progress bar. I changed this as well (again not reflected in the versions you are testing) so now it doesn't start at 0 but even on the first page fills in e.g. a quarter of the bar of a four page survey and all of it on the last page. No need to report it for others you are testing.

Since there are no other issue specific to this questionnaire I am closing this issue as well but please feel free to reopen if you disagree.

-
