### ISSUE TITLE
ssrq

### ISSUE THREAD

**Issue by magvt** [expfactory/expfactory-experiments#269]
1) Tiny radio buttons and font. 
2) Repetition - not sure if it's intentional.
![ssrq repetition](https://cloud.githubusercontent.com/assets/17258830/13122426/ce1ca20e-d584-11e5-8095-d59aa6974b2b.jpg)
3) Typo - should be "decisions"
![ssrq typo](https://cloud.githubusercontent.com/assets/17258830/13122437/dca65946-d584-11e5-9697-9927aaf93ee2.jpg)
4) Typo - most of the time *I* don't pay attention
![ssrq typo2](https://cloud.githubusercontent.com/assets/17258830/13122469/062f3526-d585-11e5-81f0-baea218476da.jpg)

**Comment by zenkavi** [comment]
2. sorry, i think i'm missing the repetition here. Is there a duplicated question or the do the questions seem like they are repetitive because they are asking very similar thing?

3,4. Done in pr #281.

also was the next button appearing in the correct place and working in this case?

**Comment by magvt** [comment]
For repetition, see the first screen shot - look at the second and last sentences.  Not exactly the same, but the difference is subtle.  I don't think that was the only example.
The next button did not appear in the correct place. And if I click into every response, the next button stays in the same place.  However - if I tab into the next question, the next button goes to the bottom.  Same - if I skip a question and hit OK on hat error message, the Next button goes into place at the bottom.
But no matter what I do or where the next button is on the initial screen, it always sends me to the bottom of the next screen.
I hope that makes sense.

**Comment by zenkavi** [comment]
Ah! I see it now! Nice catch! But unfortunately I can't change that because that is how the questionnaire is phrased indeed, so it's intentional (and strangely enough those two questions have slightly different loadings on the constructs they are thought to measure). 

I'm going to close this issue now because the other issues (next, font and radio button size) are general thing I'm working on for all questionnaires anyway and there isn't any other specific changes left for this survey. Please let me know/feel free to reopen if you disagree. Thanks.
