### ISSUE TITLE
Strange 404 errors for adaptive_n_back

### ISSUE THREAD

**Issue by vsoch** [expfactory/expfactory-experiments#57]
The strange 404 errors seem to be related to some reference of divs as files that the script is asking to retrieve:

![image](https://cloud.githubusercontent.com/assets/814322/12488651/831cf86c-c021-11e5-95ee-8555d100a2cd.png)

It appears that all the text has classes defined without parens, so they are being called as functions. I am testing this now.

**Comment by vsoch** [comment]
That didn't fix - I think it has to do something with the trial is_html being true and then trying to dynamically add to the page, [here](https://github.com/expfactory/expfactory-battery/blob/master/static/js/jspsych/poldrack_plugins/jspsych-poldrack-single-stim.js#L44). We definitely have this error for other tasks, so this might help to trace it - there are just a large number of them for this particular task.

**Comment by vsoch** [comment]
This is a known error in jspsych, and for our continuous integration I've added a hack that will prevent these errors from triggering errors, so I'm going to close this for now. If we see issue with these messages in the future we can revisit.

**Comment by jodeleeuw** [comment]
FYI, this is because jspsych is trying to automatically pre-load the value of the `stimulus` parameter as an image file. The automatic pre-loading in jspsych can't yet distinguish between an image path and an HTML string. Unfortunately there is no way to suppress these errors in code. I'm hoping to improve the automatic pre-loading in a future version to avoid trying to load non-image files.

**Comment by vsoch** [comment]
I can also help to look at this issue in the future - for now we suppress those particular errors in the continuous integration environment so the tests don't fail.
